In [11]:
import pandas as pd
from IPython.display import display

In [13]:
# pubg_df = pd.read_csv(r"C:\\Users\\Owner\\Downloads\\10.tsv", sep="\t")
df1_skillChallenge = pd.read_csv(r"C:\\Users\\Owner\\Desktop\\pubg_data\\dataset\\Skill-Challenge\\phase-wise-features\\0.tsv", sep="\t")
df2_skillChallenge = pd.read_csv(r"C:\\Users\\Owner\\Desktop\\pubg_data\\dataset\\Skill-Challenge\\phase-wise-features\\1.tsv", sep="\t")
df3_skillChallenge = pd.read_csv(r"C:\\Users\\Owner\\Desktop\\pubg_data\\dataset\\Skill-Challenge\\phase-wise-features\\2.tsv", sep="\t")
df4_skillChallenge = pd.read_csv(r"C:\\Users\\Owner\\Desktop\\pubg_data\\dataset\\Skill-Challenge\\phase-wise-features\\3.tsv", sep="\t")
df5_skillChallenge = pd.read_csv(r"C:\\Users\\Owner\\Desktop\\pubg_data\\dataset\\Skill-Challenge\\phase-wise-features\\4.tsv", sep="\t")
df6_skillChallenge = pd.read_csv(r"C:\\Users\\Owner\\Desktop\\pubg_data\\dataset\\Skill-Challenge\\phase-wise-features\\5.tsv", sep="\t")
df7_skillChallenge = pd.read_csv(r"C:\\Users\\Owner\\Desktop\\pubg_data\\dataset\\Skill-Challenge\\phase-wise-features\\6.tsv", sep="\t")
df8_skillChallenge = pd.read_csv(r"C:\\Users\\Owner\\Desktop\\pubg_data\\dataset\\Skill-Challenge\\phase-wise-features\\7.tsv", sep="\t")
df9_skillChallenge = pd.read_csv(r"C:\\Users\\Owner\\Desktop\\pubg_data\\dataset\\Skill-Challenge\\phase-wise-features\\8.tsv", sep="\t")
df10_skillChallenge = pd.read_csv(r"C:\\Users\\Owner\\Desktop\\pubg_data\\dataset\\Skill-Challenge\\phase-wise-features\\9.tsv", sep="\t")
# print(pubg_df.head())

In [29]:
# display(df1_skillChallenge.head())
# print(df1_skillChallenge.info)
df1_skillChallenge['map_name'].value_counts()
df1_skillChallenge['split'].value_counts()

split
train    3335228
test      389301
val       384778
Name: count, dtype: int64

In [15]:
display(df2_skillChallenge.head())

,match_id,snapshot,elapsed_time,player_id,player_name,team_id,loc_x,loc_y,loc_z,health,...,num_alive_teams,safety_zone_radius,map_name,team_size,num_players,ranking,ranking_scaled_proximity_danger,total_phase_damage,phase_mortality,split
0,match_959,52,0.294464,pid_79318,pname_22267,0,6272.7840,5910.0474,76.699280,1600.0,...,0.714286,3.164337,3.0,4,128,1.0,10.932940,0.0,7.142857,train
1,match_959,52,0.294464,pid_51079,pname_22267,0,3915.7244,6094.1626,82.318090,1600.0,...,0.714286,3.164337,3.0,4,128,1.0,12.435480,0.0,7.142857,train
2,match_959,52,0.294464,pid_73348,pname_22267,0,3825.5178,6027.8080,86.803690,1600.0,...,0.714286,3.164337,3.0,4,128,1.0,12.522564,0.0,7.142857,train
3,match_959,52,0.294464,pid_88538,pname_22267,0,3733.3088,6548.8690,65.800150,1600.0,...,0.714286,3.164337,3.0,4,128,1.0,11.985166,0.0,7.142857,train
4,match_959,52,0.294464,pid_50432,pname_22267,0,5258.2637,5971.4727,69.412056,1600.0,...,0.714286,3.164337,3.0,4,128,1.0,11.743152,0.0,7.142857,train

In [16]:
display(df3_skillChallenge.head())

,match_id,snapshot,elapsed_time,player_id,player_name,team_id,loc_x,loc_y,loc_z,health,...,num_alive_teams,safety_zone_radius,map_name,team_size,num_players,ranking,ranking_scaled_proximity_danger,total_phase_damage,phase_mortality,split
0,match_1079,79,0.444496,pid_102276,pname_2628,26,3069.4556,4836.6475,7.4831,100.0,...,0.548387,1.224588,0.0,4,99,0.897959,27.058083,0.0,6.122449,train
1,match_1079,79,0.444496,pid_52947,pname_93963,26,3102.9702,4847.6220,5.9250,100.0,...,0.548387,1.224588,0.0,4,99,0.887755,27.058393,0.0,6.122449,train
2,match_1407,72,0.405588,pid_96032,pname_14889,2,2330.1860,1018.3128,14.0384,100.0,...,0.775862,2.036997,11.0,4,126,0.696000,20.113762,0.0,-4.545454,train
3,match_1079,79,0.444496,pid_5874,pname_101759,15,2559.1516,3245.3428,65.1977,92.0,...,0.548387,1.224588,0.0,4,99,0.816327,28.297688,93.0,6.122449,train
4,match_1079,79,0.444496,pid_28774,pname_79818,3,4808.1770,3567.1938,31.1075,100.0,...,0.548387,1.224588,0.0,4,99,0.755102,27.261220,0.0,6.122449,train

In [17]:
display(df4_skillChallenge.head())

,match_id,snapshot,elapsed_time,player_id,player_name,team_id,loc_x,loc_y,loc_z,health,...,num_alive_teams,safety_zone_radius,map_name,team_size,num_players,ranking,ranking_scaled_proximity_danger,total_phase_damage,phase_mortality,split
0,match_432,91,0.511116,pid_54501,pname_83248,4,3982.3088,4488.133,48.750800,100.0,...,0.545455,1.120348,3.0,4,126,0.528,48.372180,0.000000,3.750000,train
1,match_432,91,0.511116,pid_29570,pname_1200,6,3423.0770,4302.976,52.243500,100.0,...,0.545455,1.120348,3.0,4,126,0.440,48.299732,0.000000,3.750000,train
2,match_1600,94,0.527778,pid_68995,pname_22267,0,3853.4763,6088.564,82.407690,1600.0,...,0.322581,0.957323,3.0,4,126,1.000,17.191180,0.000000,-3.389831,train
3,match_1600,94,0.527778,pid_46091,pname_22267,0,6326.6740,5836.094,69.932076,1600.0,...,0.322581,0.957323,3.0,4,126,1.000,14.017836,0.000000,-3.389831,train
4,match_432,91,0.511116,pid_42731,pname_16189,3,4015.3252,3404.694,96.793304,79.0,...,0.545455,1.120348,3.0,4,126,0.728,48.717937,65.439995,3.750000,train

In [18]:
display(df5_skillChallenge.head())

,match_id,snapshot,elapsed_time,player_id,player_name,team_id,loc_x,loc_y,loc_z,health,...,num_alive_teams,safety_zone_radius,map_name,team_size,num_players,ranking,ranking_scaled_proximity_danger,total_phase_damage,phase_mortality,split
0,match_2243,49,0.279550,pid_92376,pname_96754,4,2847.7156,4761.1790,6.4334,77.041756,...,0.000000,0.126750,10.0,4,17,1.000000,0.000000,0.00000,0.000000,train
1,match_2243,48,0.275023,pid_92376,pname_96754,4,2847.7156,4761.1790,6.4334,75.041756,...,0.000000,0.126750,10.0,4,17,1.000000,0.000000,0.00000,0.000000,train
2,match_1322,110,0.616667,pid_107617,pname_41663,27,6149.4220,2583.4630,5.9864,100.000000,...,0.400000,0.635459,0.0,4,91,0.888889,26.842512,21.95211,7.894737,train
3,match_1322,116,0.650017,pid_107328,pname_89609,23,5702.9020,2523.1401,1.8465,85.192180,...,0.333333,0.371938,0.0,4,91,0.666667,25.080452,7.00000,7.894737,train
4,match_1322,116,0.650017,pid_83416,pname_107091,27,6174.3413,2593.2646,6.1142,100.000000,...,0.333333,0.371938,0.0,4,91,0.966667,25.194643,0.00000,7.894737,train

In [19]:
display(df6_skillChallenge.head())

,match_id,snapshot,elapsed_time,player_id,player_name,team_id,loc_x,loc_y,loc_z,health,...,num_alive_teams,safety_zone_radius,map_name,team_size,num_players,ranking,ranking_scaled_proximity_danger,total_phase_damage,phase_mortality,split
0,match_2486,127,0.711138,pid_51102,pname_4841,3,3254.1138,6944.7495,2.89680,98.00000,...,0.225806,0.368266,0.0,4,96,0.947368,15.761854,0.0,10.000000,train
1,match_2486,127,0.711138,pid_68826,pname_6704,7,3416.1611,7170.8945,-3.69150,100.00000,...,0.225806,0.368266,0.0,4,96,0.905263,15.991910,0.0,10.000000,train
2,match_1335,132,0.738976,pid_9990,pname_22267,0,3755.3447,6475.3550,69.71747,-14.00000,...,0.161290,0.188604,3.0,4,126,1.000000,5.837811,0.0,13.333333,test
3,match_1335,131,0.733336,pid_88538,pname_22267,0,5242.0940,5907.4795,72.55378,1600.00000,...,0.161290,0.250141,3.0,4,126,1.000000,6.098185,0.0,13.333333,test
4,match_1335,132,0.738976,pid_46091,pname_22267,0,3708.2932,6568.1387,64.45257,-13.38269,...,0.161290,0.188604,3.0,4,126,1.000000,5.797238,0.0,13.333333,test

In [20]:
display(df7_skillChallenge.head())

,match_id,snapshot,elapsed_time,player_id,player_name,team_id,loc_x,loc_y,loc_z,health,...,num_alive_teams,safety_zone_radius,map_name,team_size,num_players,ranking,ranking_scaled_proximity_danger,total_phase_damage,phase_mortality,split
0,match_2384,144,0.805646,pid_95825,pname_22267,0,6427.3850,4972.6895,49.979904,1600.0,...,0.178571,0.127536,3.0,4,127,1.000,4.672669,0.0,7.142857,train
1,match_2024,142,0.794457,pid_51079,pname_22267,0,4745.5063,3597.1057,110.689180,1600.0,...,0.166667,0.184857,3.0,4,126,1.000,5.705152,0.0,0.000000,train
2,match_2024,143,0.800005,pid_26480,pname_75202,18,3252.4285,5023.2470,60.597600,95.0,...,0.166667,0.158517,3.0,4,126,1.000,26.377028,0.0,0.000000,train
3,match_2024,143,0.800005,pid_55331,pname_110737,22,3107.4377,5102.8330,66.929300,100.0,...,0.166667,0.158517,3.0,4,126,0.704,28.178993,0.0,0.000000,train
4,match_2384,144,0.805646,pid_22043,pname_22267,0,5258.4214,1401.1672,95.788440,1600.0,...,0.178571,0.127536,3.0,4,127,1.000,5.914186,0.0,7.142857,train

In [21]:
display(df8_skillChallenge.head())

,match_id,snapshot,elapsed_time,player_id,player_name,team_id,loc_x,loc_y,loc_z,health,...,num_alive_teams,safety_zone_radius,map_name,team_size,num_players,ranking,ranking_scaled_proximity_danger,total_phase_damage,phase_mortality,split
0,match_20,153,0.855574,pid_21579,pname_19108,100009,4546.1724,2573.4660,30.705568,100.0,...,0.040000,0.063562,10.0,1,99,1.000000,2.952297,0.0,25.0,train
1,match_20,153,0.855574,pid_105753,pname_46895,100012,4502.7695,2576.4966,30.323800,100.0,...,0.040000,0.063562,10.0,1,99,0.989796,2.963015,0.0,25.0,train
2,match_2307,155,0.866791,pid_2720,pname_22267,0,3805.0210,6177.7607,82.547160,1600.0,...,0.035714,0.092429,3.0,4,124,1.000000,2.452049,0.0,0.0,train
3,match_2307,155,0.866791,pid_68995,pname_22267,0,3711.4763,6563.8125,64.540860,1600.0,...,0.035714,0.092429,3.0,4,124,1.000000,2.367118,0.0,0.0,train
4,match_2307,155,0.866791,pid_93436,pname_22267,0,5202.0230,5889.1380,77.679720,1600.0,...,0.035714,0.092429,3.0,4,124,1.000000,2.725528,0.0,0.0,train

In [22]:
display(df9_skillChallenge.head())

,match_id,snapshot,elapsed_time,player_id,player_name,team_id,loc_x,loc_y,loc_z,health,...,num_alive_teams,safety_zone_radius,map_name,team_size,num_players,ranking,ranking_scaled_proximity_danger,total_phase_damage,phase_mortality,split
0,match_1439,142,0.796827,pid_33939,pname_77386,17,1970.7072,2749.3271,1.6959,75.00,...,0.028571,0.038223,8.0,4,96,1.0,0.000000,0.00000,0.0,train
1,match_1439,142,0.796827,pid_97592,pname_109061,17,1981.5027,2752.2422,2.3696,80.45,...,0.028571,0.038223,8.0,4,96,1.0,0.000000,0.00000,0.0,train
2,match_757,161,0.900049,pid_28238,pname_17235,3,5983.7340,2494.0918,1.1906,100.00,...,0.066667,0.039679,0.0,4,94,1.0,1.962536,67.67999,50.0,train
3,match_757,161,0.900049,pid_53857,pname_96118,3,5962.6655,2498.8380,0.9106,100.00,...,0.066667,0.039679,0.0,4,94,1.0,1.963857,0.00000,50.0,train
4,match_1439,142,0.796827,pid_51711,pname_55799,17,1970.7701,2750.2770,1.6422,0.00,...,0.028571,0.038223,8.0,4,96,1.0,0.000000,0.00000,0.0,train

In [23]:
display(df10_skillChallenge.head())

,match_id,snapshot,elapsed_time,player_id,player_name,team_id,loc_x,loc_y,loc_z,health,...,num_alive_teams,safety_zone_radius,map_name,team_size,num_players,ranking,ranking_scaled_proximity_danger,total_phase_damage,phase_mortality,split
0,match_2207,187,1.044666,pid_68275,pname_26190,6,3964.2075,5754.1360,22.753700,75.00,...,0.066667,0.049355,6.0,4,50,1.000000,0.000000,56.400000,0.0,train
1,match_2207,187,1.044666,pid_79458,pname_3675,6,3994.8997,5743.9660,18.294500,51.63,...,0.066667,0.049355,6.0,4,50,1.000000,0.000000,123.369995,0.0,train
2,match_281,170,0.950219,pid_93436,pname_22267,0,6251.2640,5968.6430,74.506620,1600.00,...,0.031250,0.023107,3.0,4,122,1.000000,2.067542,0.000000,0.0,val
3,match_2207,185,1.033341,pid_18131,pname_23837,11,4000.8503,5747.5650,18.325900,0.00,...,0.133333,0.059023,6.0,4,50,0.938776,2.990102,100.000000,0.0,train
4,match_2207,189,1.056781,pid_25663,pname_29519,6,3964.9890,5776.9883,18.659399,86.00,...,0.000000,0.049355,6.0,4,50,1.000000,0.000000,91.025990,0.0,train